services:
  - type: web
    name: mysite
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false # You'll provide this value on Blueprint creation
      - key: WEB_CONCURRENCY
        value: 2 # Recommended default
    domains:
      - cityonthecoast.com
    healthCheckPath: "/up"
    autoDeployTrigger: checksPass
databases:
  - name: mysite-db
    plan: basic-256mb
    ipAllowList: [] # Only allow internal connections
